apiVersion: v1
kind: Service
metadata:
  name: my-service 
spec:
  selector:
    app: myapp #it should be matched with the label in the deployment or replicaset
  ports:
  - port: 3000
    targetPort: 80
